knowledges:
  # bisheng-uns服务地址填写示例： http://ip:port/v1/etl4llm/predict
  unstructured_api_url: ""  # 毕昇非结构化数据解析服务地址，提供包括OCR文字识别、表格识别、版式分析等能力。非必填，溯源必填

llm_request:
  # 模型访问的超时配置
  request_timeout: 600
  # 失败的重试次数
  max_retries: 1

# v2免登录接口使用的默认操作用户
default_operator:
  user: 3
  url: https://bisheng.dataelem.com
  # 免登录接口是否校验权限
  api_need_login: false

# 是否需要验证码
use_captcha:
  False

# 聊天对话框配置
dialog_tips:
  "内容由AI生成，仅供参考！"

env:
  # 聊天窗口支持快捷搜索的搜索引擎
  # dialog_quick_search: http://www.baidu.com/s?wd=
  # 可配置与http不一致的websocket地址
  # websocket_url: 192.168.106.120:3003
  office_url: http://IP:8701 # office 组件访问地址，需要浏览器能直接访问
  # 是否展示前端界面上的github和帮助链接
  show_github_and_help: true

# 密码配置
password_conf:
  # 密码超过X天必须进行修改, 登录提示重新修改密码。大于0策略才生效
  password_valid_period: 180
  # 登录错误时间窗口,单位分钟。在错误时间窗口内超过最大错误次数会封禁用户。两个值都大于0才生效
  login_error_time_window: 10
  # 最大错误次数，超过后会封禁用户
  max_error_times: 5

system_login_method:
  # 是否支持闭源网关的登录
  gateway_login: false
  # 从闭源网关注册的管理员用户名
  admin_username: admin
  # 是否允许多点登录
  allow_multi_login: true

