data:
  origin_file_path: '/home/public/rag_benchmark_v1.0/rag_benchmark_processed'
  question: '/home/gulixin/workspace/llm/bisheng/src/bisheng-langchain/experimental/rag/data/questions_info_with_answer_sample.xlsx'
  save_answer: '/home/gulixin/workspace/llm/bisheng/src/bisheng-langchain/experimental/rag/data/questions_info_with_answer_sample_gpt4_12chunk_test.xlsx'

milvus:
  host: '192.168.106.116'
  port: '19530'
  drop_old: True

elasticsearch:
  url: 'http://192.168.106.116:9200'
  ssl_verify:
    basic_auth: ["elastic", "oSGL-zVvZ5P3Tm7qkDLC"]
  drop_old: True

embedding:
  type: 'OpenAIEmbeddings'
  model: 'text-embedding-ada-002'
  openai_api_key: 'xxxx'
  openai_proxy: 'http://118.195.232.223:39995'

chat_llm:
  type: 'ChatOpenAI'
  model: 'gpt-4-1106-preview'
  openai_api_key: 'xxxx'
  openai_proxy: 'http://118.195.232.223:39995'
  temperature: 0.0

# chat_llm:
#   type: 'ChatQWen'
#   model_name: 'qwen-1.8b-chat'
#   api_key: 'xxxx'
#   temperature: 0.0

# chat_llm:
#   type: 'HostQwenChat'
#   model_name: 'qwen-1_8B-benchmarkv1-ganrao-8192-epoch10-filter-export'
#   host_base_url: 'http://34.142.140.180:7001/v2.1/models'
#   temperature: 0.0

knowledge:
  loader: 
    type: 'ElemUnstructuredLoader'
    unstructured_api_url: 'http://192.168.106.20:10001/v1/etl4llm/predict'
  splitter: 
    type: 'ElemCharacterTextSplitter'
    chunk_size: 500
    chunk_overlap: 50
    separators: ['\n\n', '\n', ' ', '']
  save_milvus: True
  save_es: True
  suffix: 'test_glx'

retrieval_rerank:
  retrieval:
    type: 'base' 
    mode: 'hybrid' # 'keyword' or 'vector' or 'hybrid'
    combine_strategy: 'mix' # 'mix' or 'keyword_front' or 'vector_front'
    search_type: 'similarity'
    chunk_num: 6
  delete_duplicate: False
  with_rank: False
  rerank:
    type: 'CustomReranker'
    model_path: '/home/public/llm/bge-reranker-large'
    device_id: 'cuda:0'
    threshold: 0.0

generate:
  with_retrieval: True
  chain_type: 'stuff'

metric:
  type: 'bisheng-ragas'
  question_column: '问题'
  gt_column: 'GT'
  answer_column: 'rag_answer'
  query_type_column: '问题类型'
  metrics: ['answer_correctness_bisheng']
  batch_size: 5